### ISSUE TITLE
Properties defined multiple times

### ISSUE THREAD

**Issue by cecilemuller** [wildpeaks/json-scenegraph#2]
A question from the [X3D mailing-list](http://web3d.org/pipermail/x3d-public_web3d.org) referencing wildpeaks/json-scenegraph#1 :

> Something that jumps out is when you say _"How would you make a Group that contains a Shape, a Transform and another Shape ? It can't be the following because an Object can't define property Shape twice"_.
> 
> That is indeed a serious constraint, if it is indeed correct - that wasn't clear about Javascript.  (got a reference?)

**Comment by coderextreme** [comment]
How was this closed?

**Comment by cecilemuller** [comment]
Oh sorry I didn't see your comment until now.

It was closed because using duplicated keys in objects is not an option (otherwise it would be up to debate), it's a technical constraint to be compatible with native parsers like Javascript's JSON.parse.
